Repository jenkins-x-plugins/jx-changelog, pull requests merged in 2021-11, with the labels that each got.

#23 feat: Support outputting markdown to file as well as to release manifest
  docs/cmd/jx-changelog.md
  docs/cmd/jx-changelog_create.md
  docs/cmd/jx-changelog_version.md
  docs/man/man1/jx-changelog-create.1
  pkg/cmd/create/create.go
  pkg/cmd/create/create_test.go
Labels: size/S, ok-to-test, lgtm, approved

#25 feat: Support Jira as issue tracker when creating changelog
  go.mod
  go.sum
  pkg/cmd/create/create.go
Labels: ok-to-test, lgtm, approved, size/XL

#26 chore: fix release pipeline
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/XS

#27 chore: comment out cosign step while bug that is replacing the secret is fixed
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/XS

#28 refactor: add lint step and fix linting issues
  .golangci.yml
  .lighthouse/jenkins-x/lint.yaml
  .lighthouse/jenkins-x/triggers.yaml
  cmd/app/main.go
  hack/linter.sh
  pkg/cmd/create/create.go
  pkg/gits/commits.go
  pkg/gits/helpers.go
  pkg/issues/git_provider.go
  pkg/issues/jira.go
  pkg/users/resolver.go
Labels: lgtm, approved, size/L
