Repository jenkins-x-plugins/jx-changelog, pull requests merged in 2021-01, with the labels that each got.

#4 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/S, updatebot

#5 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/M, updatebot

#7 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/S, updatebot

#8 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: updatebot

#9 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: updatebot

#10 chore: upgrade dependencies
  go.mod
  go.sum
Labels: approved

#12 chore: upgrade dependencies
  go.mod
Labels: approved, lgtm, ok-to-test, size/XS

#13 chore: update dependencies
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/XS

#14 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/L, updatebot
