Repository jenkins-x-plugins/jx-changelog, pull requests merged in 2022-07, with the labels that each got.

#33 feat: upgrade go to 1.17
  .lighthouse/jenkins-x/lint.yaml
  cmd/docs/main.go
  go.mod
  go.sum
  pkg/cmd/create/create.go
  pkg/cmd/create/create_test.go
  pkg/issues/git_provider.go
  pkg/issues/jira.go
Labels: approved, size/XXL

#31 fix: creating codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: size/M, ok-to-test, lgtm, approved

#34 fix: replace jwt-go with golang-jwt
  go.mod
  go.sum
Labels: size/M, approved
