Repository jenkins-x-plugins/jx-changelog, pull requests merged in 2022-09, with the labels that each got.

#36 feat: Show breaking changes
  OWNERS
  OWNERS_ALIASES
  pkg/gits/commits.go
  pkg/gits/commits_integration_test.go
  pkg/gits/commits_test.go
Labels: size/L

#35 fix: reduce changelog image size by removing unrelated binaries
  Dockerfile
Labels: approved, size/XS

#37 feat: add supply chain security
  .gitignore
  .goreleaser.yml
  .lighthouse/jenkins-x/release.yaml
Labels: size/M, ok-to-test, approved

#38 fix: add git to changelog image
  Dockerfile
Labels: approved, size/XS

#40 refactor: upgrade go version to 1.18.6
  Makefile
  go.mod
  go.sum
Labels: approved, size/L
