Repository jenkins-x-plugins/jx-changelog, pull requests merged in 2025-07, with the labels that each got.

#81 fix: Avoid crash when running against Gitlab
  pkg/cmd/create/create.go
Labels: ok-to-test, approved, size/XS

#74 fix: show correct usage of sub commands
  pkg/cmd/root.go
  pkg/common/helpers.go
  pkg/rootcmd/constants.go
Labels: size/S, approved

#84 fix: ensure git user details are set
  pkg/cmd/create/create_test.go
Labels: approved, size/XS
